name: carbnote
description: Carb Note
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_remote_config: ^0.6.0
  firebase_storage: ^7.0.0
  flutter_hooks: ^0.15.0
  freezed_annotation: ^0.12.0
  hooks_riverpod: ^0.12.3+1
  image_picker: ^0.6.7+22
  intl: ^0.16.1
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  flutter_native_splash: ^0.3.0
  freezed: ^0.12.7
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700

flutter_native_splash:
  color: '#5663FF'
